### ISSUE TITLE
File cactusplot_syrup_vs_syrup_gpu.eps is missing

### ISSUE THREAD

**Issue by msoos** [nicolasprevot/GpuShareSatPresentation#1]
Attached. Please add to the codbase. Thanks,

Mate

**Comment by nicolasprevot** [comment]
There is already the pdf version: cactusplot_syrup_vs_syrup_gpu.pdf

**Comment by msoos** [comment]
Hi,

Unfortunately, you are missing the cactusplot_syrup_vs_syrup_gpu file. You only have the`cactusplot_painless_vs_relaxed_gpu.pdf` in the repository, but you (also) refer to `cactusplot_syrup_vs_syrup_gpu` in the presentation. When I compile with pdflatex:
```
Overfull \hbox (63.46188pt too wide) has occurred while \output is active
 [][][][]  
[14 <./clauseTest.png>]

! LaTeX Error: File `cactusplot_syrup_vs_syrup_gpu' not found.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.256 \end{frame}
```

I wrote this issue because I could not compile the presentation. Can you please add it? Thanks,

Mate

**Comment by nicolasprevot** [comment]
Added, sorry about that
